caddy_features: http.cgi,http.prometheus
caddy_setcap: yes
caddy_systemd_capabilities_enabled: True
caddy_systemd_capabilities: "CAP_NET_BIND_SERVICE"
caddy_config: |
  m3.noisebridge.net {
    gzip
    tls ca@noisebridge.net
  }

