---
pydonate_version: HEAD
pydonate_user: pydonate
pydonate_port: 8888
pydonate_config:
  secrets:
    db_pass: nope
    donate_product: nope
    donate_secret: nope
    stripe_key: nope
    stripe_secret: nope
