---
users:
  beka:
    fullname: ''
    email: ...

  chaz:
    fullname: 'chaz'
    github_username: chazchaz101

  cole:
    fullname: ''
    email: ...

  cowlicks:
    fullname: 'blake,,,'
    email: ...

  danh:
    fullname: ...
    email: ...
    github_username: danhimalplanet

  eenblam:
    fullname: ''
    email: ...

  elf:
    fullname: ''
    email: ...

  gareth:
    fullname: ',,,'
    email: ...

  hzeller:
    fullname: 'Henner Zeller,,,'
    email: ...

  jams:
    fullname: 'Jeremy,,,'
    email: ...

  jerm:
    fullname: ',,,'
    email: ...

  jof:
    fullname: 'Jonathan Lassoff,,,'
    email: ...

  lizzie:
    fullname: ',,,'
    email: ...

  miloh:
    fullname: 'Ronald Miloh Alexander,,,'
    email: ...

  nthmost:
    fullname: 'Naomi Most,,,'
    email: ...

  patrickod:
    fullname: Patrick O'Doherty
    email: p@trickod.com
    github_username: patrickod

  r:
    fullname: ',,,'
    email: ...

  rando:
    fullname: 'Matthew Arcidy,,,'
    email: ...

  robbintt:
    fullname: 'Robin Trent'
    email: ...

  steele:
    fullname: 'Lee Azzarello,,,'
    email: ...

  superq:
    fullname: Ben Kochie
    email: superq@gmail.com
    github_username: superq

  tdfischer:
    fullname: 'Torrie Fischer,,,'
    email: ...

  teapot:
    fullname: 'Bill Williams,,,'
    email: ...
