coredns_user: coredns
coredns_port: 53

coredns_path: /srv/coredns
coredns_version: "1.0.6"
coredns_download_url: https://github.com/coredns/coredns/releases/download

coredns_config: |
  .:53 {
    proxy . 8.8.8.8:53
    errors stdout
  }
