---
caddy_features: http.cgi,http.prometheus
caddy_setcap: yes
caddy_systemd_capabilities_enabled: True
caddy_systemd_capabilities: "CAP_NET_BIND_SERVICE"
caddy_config: |
  noisebridge.com, www.noisebridge.com {
    prometheus
    gzip
    log "{{ caddy_log_dir }}/noisebridge.com.log" {
      rotate_size 50
      rotate_age 7
      rotate_keep 520
      rotate_compress
    }
    tls ca@noisebridge.net
    redir https://www.noisebridge.net{uri}
  }

  noisebridge.net {
    prometheus
    gzip
    log "{{ caddy_log_dir }}/noisebridge.net.log" {
      rotate_size 50
      rotate_age 7
      rotate_keep 520
      rotate_compress
    }
    tls ca@noisebridge.net
    redir https://www.noisebridge.net{uri}
  }

  www.noisebridge.net {
    prometheus
    gzip
    log "{{ caddy_log_dir }}/www.noisebridge.net.log" {
      rotate_size 50
      rotate_age 7
      rotate_keep 520
      rotate_compress
    }
    tls ca@noisebridge.net

    root /srv/mediawiki/noisebridge.net

    index index.php

    header / {
      Strict-Transport-Security "max-age=31536000;includeSubdomains"
      X-XSS-Protection "1; mode=block"
      X-Content-Type-Options "nosniff"
    }

    fastcgi / unix:/run/php/php7.0-fpm.sock php {
        except /images
    }

    rewrite / {
        r /(.*)
        to {path} {path}/ /index.php?title={1}
    }
  }

  www.noisebridge.net/pipermail/ {
    prometheus
    log "{{ caddy_log_dir }}/www.noisebridge.net-pipermail.log" {
      rotate_size 50
      rotate_age 7
      rotate_keep 520
      rotate_compress
    }
    redir https://lists.noisebridge.net{uri}
  }

  www.noisebridge.net/mailman/ {
    prometheus
    log "{{ caddy_log_dir }}/www.noisebridge.net-mailman.log" {
      rotate_size 50
      rotate_age 7
      rotate_keep 520
      rotate_compress
    }
    redir https://lists.noisebridge.net{uri}
  }

  lists.noisebridge.net {
    prometheus
    gzip
    log "{{ caddy_log_dir }}/lists.noisebridge.net.log" {
      rotate_size 50
      rotate_age 7
      rotate_keep 520
      rotate_compress
    }
    tls ca@noisebridge.net
    root /srv/mailman/lists.noisebridge.net
    redir / /mailman/listinfo
  }

  lists.noisebridge.net/mailman/ {
    prometheus
    log "{{ caddy_log_dir }}/lists.noisebridge.net-mailman.log" {
      rotate_size 50
      rotate_age 7
      rotate_keep 520
      rotate_compress
    }
    cgi /* /var/lib/mailman/cgi-bin/{match}

    redir /mailman /mailman/listinfo
  }

  lists.noisebridge.net/pipermail/ {
    prometheus
    gzip
    log "{{ caddy_log_dir }}/lists.noisebridge.net-pipermail.log" {
      rotate_size 50
      rotate_age 7
      rotate_keep 520
      rotate_compress
    }
    tls ca@noisebridge.net
    root /var/lib/mailman/archives/public
    index index.html
  }

  lists.noisebridge.net/images/mailman/ {
    prometheus
    gzip
    log "{{ caddy_log_dir }}/lists.noisebridge.net-images-mailman.log" {
      rotate_size 50
      rotate_age 7
      rotate_keep 520
      rotate_compress
    }
    tls ca@noisebridge.net
    root /var/lib/mailman/icons/
  }

  noisebridge.org, www.noisebridge.org {
    prometheus
    gzip
    log "{{ caddy_log_dir }}/noisebridge.org.log" {
      rotate_size 50
      rotate_age 7
      rotate_keep 520
      rotate_compress
    }
    tls ca@noisebridge.net
    redir https://www.noisebridge.net{uri}
  }
