---
caddy_features: http.cgi,http.prometheus
caddy_setcap: yes
caddy_systemd_capabilities_enabled: True
caddy_systemd_capabilities: "CAP_NET_BIND_SERVICE"
caddy_config: |

  www.noisebridge.net {
    gzip
    tls ca@noisebridge.net

    root /srv/mediawiki/noisebridge.net

    index index.php

    header / {
      Strict-Transport-Security "max-age=31536000;includeSubdomains"
      X-XSS-Protection "1; mode=block"
      X-Content-Type-Options "nosniff"
    }

    fastcgi / unix:/run/php/php7.0-fpm.sock php {
        except /images
    }

    rewrite / {
        r /(.*)
        to {path} {path}/ /index.php?title={1}
    }
  }

  noisebridge.net {
    gzip
    tls ca@noisebridge.net
    redir https://www.noisebridge.net{uri}
  }

  lists.noisebridge.net {
    gzip
    tls ca@noisebridge.net
    root /srv/mailman/lists.noisebridge.net
    redir / /mailman/listinfo
  }

  lists.noisebridge.net/mailman/ {
    cgi /* /var/lib/mailman/cgi-bin/{match}

    redir /mailman /mailman/listinfo
  }

  lists.noisebridge.net/pipermail/ {
    gzip
    tls ca@noisebridge.net
    root /var/lib/mailman/archives/public
    index index.html
  }

  lists.noisebridge.net/images/mailman/ {
    gzip
    tls ca@noisebridge.net
    root /var/lib/mailman/icons/
  }
