---
caddy_packages:
- 'github.com/aksdb/caddy-cgi/v2@v2.2.1'
- 'github.com/greenpau/caddy-security@v1.1.20'
- 'github.com/mholt/caddy-ratelimit@v0.1.0'
caddy_config: "{{ lookup('template', 'templates/caddy/m3/Caddyfile.j2') }}"

noisebridge_mailman_cgi_scripts:
- admin
- admindb
- confirm
- create
- edithtml
- listinfo
- options
- private
- rmlist
- roster
- subscribe
